ab_url: "https://codgis.itos.uga.edu/arcgis/rest/services/COD_External"

em_url: "https://codgis.itos.uga.edu/arcgis/rest/services/COD_External_Edgematch"

ps_url: "https://apps.itos.uga.edu/CODV2API/api/v1/themes/cod-ps/lookup/Get/adm/do/iso"
