# This workflow will install Python dependencies and run the script

name: run

on:
  workflow_dispatch: # add run button in GitHub UI

jobs:
  run:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.9
      uses: actions/setup-python@v2
      with:
        python-version: '3.x'
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
    - name: Run script
      env:
        HDX_SITE: ${{ secrets.HDX_SITE }}
        HDX_KEY: ${{ secrets.HDX_KEY }}
        USER_AGENT: ${{ secrets.USER_AGENT }}
        PREPREFIX: ${{ secrets.PREPREFIX }}
      run: |
        python run.py
    - name: Send mail
      if: failure()
      uses: dawidd6/action-send-mail@v2
      with:
        server_address: ${{secrets.EMAIL_SERVER}}
        server_port: ${{secrets.EMAIL_PORT}}
        username: ${{secrets.EMAIL_USERNAME}}
        password: ${{secrets.EMAIL_PASSWORD}}
        subject: "FAILED: ${{github.repository}} run job"
        body: GitHub Actions run job for ${{github.repository}} failed!
        to: ${{secrets.EMAIL_LIST}}
        from: ${{secrets.EMAIL_FROM}}
        content_type: text/html
